### ISSUE TITLE
Points for insights

### ISSUE THREAD

**Issue by dansbecker** [dataquestio/unite#8]
I think it would be nice to have a way of rewarding contributors for creating data visualizations or reporting insights that help move the team forward (even if they don't create a submission and thus don't improve our score).

Even if we don't reward points for helpful visualizations/insights, is there a policy for whether code creating these visualizations can get merged to master?

**Comment by VikParuchuri** [comment]
That makes sense.  The code will get merged right now, and you will get merge and PR open points.  

It would be interesting to assign points based on some evaluation of the visualizations/insights, but that may be better as a peer exercise.
